spring:
  datasource:
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: ${MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

jwt:
  secret: X2ZLf06S1N2AsK1MDOXTOv8fzbV+ng2aCxYrVGFi9y8=
  time:
    access-expiration: 3600000  # 1hour
    refresh-expiration: 86400000  #30일